<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
             ['name' => 'Andorra', 'ccode' => 'AD'],
             ['name' => 'United Arab Emirates', 'ccode' => 'AE'],
             ['name' => 'Afghanistan', 'ccode' => 'AF'],
             ['name' => 'Antigua and Barbuda', 'ccode' => 'AG'],
             ['name' => 'Anguilla', 'ccode' => 'AI'],
             ['name' => 'Albania', 'ccode' => 'AL'],
             ['name' => 'Armenia', 'ccode' => 'AM'],
             ['name' => 'Netherlands Antilles', 'ccode' => 'AN'],
             ['name' => 'Angola', 'ccode' => 'AO'],
             ['name' => 'Antarctica', 'ccode' => 'AQ'],
             ['name' => 'Argentina', 'ccode' => 'AR'],
             ['name' => 'American Samoa', 'ccode' => 'AS'],
             ['name' => 'Austria', 'ccode' => 'AT'],
             ['name' => 'Australia', 'ccode' => 'AU'],
             ['name' => 'Aruba', 'ccode' => 'AW'],
             ['name' => 'Azerbaijan', 'ccode' => 'AZ'],
             ['name' => 'Bosnia and Herzegovina', 'ccode' => 'BA'],
             ['name' => 'Barbados', 'ccode' => 'BB'],
             ['name' => 'Bangladesh', 'ccode' => 'BD'],
             ['name' => 'Belgium', 'ccode' => 'BE'],
             ['name' => 'Burkina Faso', 'ccode' => 'BF'],
             ['name' => 'Bulgaria', 'ccode' => 'BG'],
             ['name' => 'Bahrain', 'ccode' => 'BH'],
             ['name' => 'Burundi', 'ccode' => 'BI'],
             ['name' => 'Benin', 'ccode' => 'BJ'],
             ['name' => 'Bermuda', 'ccode' => 'BM'],
             ['name' => 'Brunei', 'ccode' => 'BN'],
             ['name' => 'Bolivia', 'ccode' => 'BO'],
             ['name' => 'Brazil', 'ccode' => 'BR'],
             ['name' => 'Bahamas', 'ccode' => 'BS'],
             ['name' => 'Bhutan', 'ccode' => 'BT'],
             ['name' => 'Bouvet Island', 'ccode' => 'BV'],
             ['name' => 'Botswana', 'ccode' => 'BW'],
             ['name' => 'Belarus', 'ccode' => 'BY'],
             ['name' => 'Belize', 'ccode' => 'BZ'],
             ['name' => 'Canada', 'ccode' => 'CA'],
             ['name' => 'Cocos [Keeling] Islands', 'ccode' => 'CC'],
             ['name' => 'Congo [DRC]', 'ccode' => 'CD'],
             ['name' => 'Central African Republic', 'ccode' => 'CF'],
             ['name' => 'Congo [Republic]', 'ccode' => 'CG'],
             ['name' => 'Switzerland', 'ccode' => 'CH'],
             ['name' => 'Cote dIvoire', 'ccode' => 'CI'],
             ['name' => 'Cook Islands', 'ccode' => 'CK'],
             ['name' => 'Chile', 'ccode' => 'CL'],
             ['name' => 'Cameroon', 'ccode' => 'CM'],
             ['name' => 'China', 'ccode' => 'CN'],
             ['name' => 'Colombia', 'ccode' => 'CO'],
             ['name' => 'Costa Rica', 'ccode' => 'CR'],
             ['name' => 'Cuba', 'ccode' => 'CU'],
             ['name' => 'Cape Verde', 'ccode' => 'CV'],
             ['name' => 'Christmas Island', 'ccode' => 'CX'],
             ['name' => 'Cyprus', 'ccode' => 'CY'],
             ['name' => 'Czech Republic', 'ccode' => 'CZ'],
             ['name' => 'Germany', 'ccode' => 'DE'],
             ['name' => 'Djibouti', 'ccode' => 'DJ'],
             ['name' => 'Denmark', 'ccode' => 'DK'],
             ['name' => 'Dominica', 'ccode' => 'DM'],
             ['name' => 'Dominican Republic', 'ccode' => 'DO'],
             ['name' => 'Algeria', 'ccode' => 'DZ'],
             ['name' => 'Ecuador', 'ccode' => 'EC'],
             ['name' => 'Estonia', 'ccode' => 'EE'],
             ['name' => 'Egypt', 'ccode' => 'EG'],
             ['name' => 'Western Sahara', 'ccode' => 'EH'],
             ['name' => 'Eritrea', 'ccode' => 'ER'],
             ['name' => 'Spain', 'ccode' => 'ES'],
             ['name' => 'Ethiopia', 'ccode' => 'ET'],
             ['name' => 'Finland', 'ccode' => 'FI'],
             ['name' => 'Fiji', 'ccode' => 'FJ'],
             ['name' => 'Falkland Islands [Islas Malvinas]', 'ccode' => 'FK'],
             ['name' => 'Micronesia', 'ccode' => 'FM'],
             ['name' => 'Faroe Islands', 'ccode' => 'FO'],
             ['name' => 'France', 'ccode' => 'FR'],
             ['name' => 'Gabon', 'ccode' => 'GA'],
             ['name' => 'United Kingdom', 'ccode' => 'GB'],
             ['name' => 'Grenada', 'ccode' => 'GD'],
             ['name' => 'Georgia', 'ccode' => 'GE'],
             ['name' => 'French Guiana', 'ccode' => 'GF'],
             ['name' => 'Guernsey', 'ccode' => 'GG'],
             ['name' => 'Ghana', 'ccode' => 'GH'],
             ['name' => 'Gibraltar', 'ccode' => 'GI'],
             ['name' => 'Greenland', 'ccode' => 'GL'],
             ['name' => 'Gambia', 'ccode' => 'GM'],
             ['name' => 'Guinea', 'ccode' => 'GN'],
             ['name' => 'Guadeloupe', 'ccode' => 'GP'],
             ['name' => 'Equatorial Guinea', 'ccode' => 'GQ'],
             ['name' => 'Greece', 'ccode' => 'GR'],
             ['name' => 'South Georgia and the South Sandwich Islands', 'ccode' => 'GS'],
             ['name' => 'Guatemala', 'ccode' => 'GT'],
             ['name' => 'Guam', 'ccode' => 'GU'],
             ['name' => 'Guinea-Bissau', 'ccode' => 'GW'],
             ['name' => 'Guyana', 'ccode' => 'GY'],
             ['name' => 'Gaza Strip', 'ccode' => 'GZ'],
             ['name' => 'Hong Kong', 'ccode' => 'HK'],
             ['name' => 'Heard Island and McDonald Islands', 'ccode' => 'HM'],
             ['name' => 'Honduras', 'ccode' => 'HN'],
             ['name' => 'Croatia', 'ccode' => 'HR'],
             ['name' => 'Haiti', 'ccode' => 'HT'],
             ['name' => 'Hungary', 'ccode' => 'HU'],
             ['name' => 'Indonesia', 'ccode' => 'ID'],
             ['name' => 'Ireland', 'ccode' => 'IE'],
             ['name' => 'Israel', 'ccode' => 'IL'],
             ['name' => 'Isle of Man', 'ccode' => 'IM'],
             ['name' => 'India', 'ccode' => 'IN'],
             ['name' => 'British Indian Ocean Territory', 'ccode' => 'IO'],
             ['name' => 'Iraq', 'ccode' => 'IQ'],
             ['name' => 'Iran', 'ccode' => 'IR'],
             ['name' => 'Iceland', 'ccode' => 'IS'],
             ['name' => 'Italy', 'ccode' => 'IT'],
             ['name' => 'Jersey', 'ccode' => 'JE'],
             ['name' => 'Jamaica', 'ccode' => 'JM'],
             ['name' => 'Jordan', 'ccode' => 'JO'],
             ['name' => 'Japan', 'ccode' => 'JP'],
             ['name' => 'Kenya', 'ccode' => 'KE'],
             ['name' => 'Kyrgyzstan', 'ccode' => 'KG'],
             ['name' => 'Cambodia', 'ccode' => 'KH'],
             ['name' => 'Kiribati', 'ccode' => 'KI'],
             ['name' => 'Comoros', 'ccode' => 'KM'],
             ['name' => 'Saint Kitts and Nevis', 'ccode' => 'KN'],
             ['name' => 'North Korea', 'ccode' => 'KP'],
             ['name' => 'South Korea', 'ccode' => 'KR'],
             ['name' => 'Kuwait', 'ccode' => 'KW'],
             ['name' => 'Cayman Islands', 'ccode' => 'KY'],
             ['name' => 'Kazakhstan', 'ccode' => 'KZ'],
             ['name' => 'Laos', 'ccode' => 'LA'],
             ['name' => 'Lebanon', 'ccode' => 'LB'],
             ['name' => 'Saint Lucia', 'ccode' => 'LC'],
             ['name' => 'Liechtenstein', 'ccode' => 'LI'],
             ['name' => 'Sri Lanka', 'ccode' => 'LK'],
             ['name' => 'Liberia', 'ccode' => 'LR'],
             ['name' => 'Lesotho', 'ccode' => 'LS'],
             ['name' => 'Lithuania', 'ccode' => 'LT'],
             ['name' => 'Luxembourg', 'ccode' => 'LU'],
             ['name' => 'Latvia', 'ccode' => 'LV'],
             ['name' => 'Libya', 'ccode' => 'LY'],
             ['name' => 'Morocco', 'ccode' => 'MA'],
             ['name' => 'Monaco', 'ccode' => 'MC'],
             ['name' => 'Moldova', 'ccode' => 'MD'],
             ['name' => 'Montenegro', 'ccode' => 'ME'],
             ['name' => 'Madagascar', 'ccode' => 'MG'],
             ['name' => 'Marshall Islands', 'ccode' => 'MH'],
             ['name' => 'Macedonia [FYROM]', 'ccode' => 'MK'],
             ['name' => 'Mali', 'ccode' => 'ML'],
             ['name' => 'Myanmar [Burma]', 'ccode' => 'MM'],
             ['name' => 'Mongolia', 'ccode' => 'MN'],
             ['name' => 'Macau', 'ccode' => 'MO'],
             ['name' => 'Northern Mariana Islands', 'ccode' => 'MP'],
             ['name' => 'Martinique', 'ccode' => 'MQ'],
             ['name' => 'Mauritania', 'ccode' => 'MR'],
             ['name' => 'Montserrat', 'ccode' => 'MS'],
             ['name' => 'Malta', 'ccode' => 'MT'],
             ['name' => 'Mauritius', 'ccode' => 'MU'],
             ['name' => 'Maldives', 'ccode' => 'MV'],
             ['name' => 'Malawi', 'ccode' => 'MW'],
             ['name' => 'Mexico', 'ccode' => 'MX'],
             ['name' => 'Malaysia', 'ccode' => 'MY'],
             ['name' => 'Mozambique', 'ccode' => 'MZ'],
             ['name' => 'Namibia', 'ccode' => 'NA'],
             ['name' => 'New Caledonia', 'ccode' => 'NC'],
             ['name' => 'Niger', 'ccode' => 'NE'],
             ['name' => 'Norfolk Island', 'ccode' => 'NF'],
             ['name' => 'Nigeria', 'ccode' => 'NG'],
             ['name' => 'Nicaragua', 'ccode' => 'NI'],
             ['name' => 'Netherlands', 'ccode' => 'NL'],
             ['name' => 'Norway', 'ccode' => 'NO'],
             ['name' => 'Nepal', 'ccode' => 'NP'],
             ['name' => 'Nauru', 'ccode' => 'NR'],
             ['name' => 'Niue', 'ccode' => 'NU'],
             ['name' => 'New Zealand', 'ccode' => 'NZ'],
             ['name' => 'Oman', 'ccode' => 'OM'],
             ['name' => 'Panama', 'ccode' => 'PA'],
             ['name' => 'Peru', 'ccode' => 'PE'],
             ['name' => 'French Polynesia', 'ccode' => 'PF'],
             ['name' => 'Papua New Guinea', 'ccode' => 'PG'],
             ['name' => 'Philippines', 'ccode' => 'PH'],
             ['name' => 'Pakistan', 'ccode' => 'PK'],
             ['name' => 'Poland', 'ccode' => 'PL'],
             ['name' => 'Saint Pierre and Miquelon', 'ccode' => 'PM'],
             ['name' => 'Pitcairn Islands', 'ccode' => 'PN'],
             ['name' => 'Puerto Rico', 'ccode' => 'PR'],
             ['name' => 'Palestinian Territories', 'ccode' => 'PS'],
             ['name' => 'Portugal', 'ccode' => 'PT'],
             ['name' => 'Palau', 'ccode' => 'PW'],
             ['name' => 'Paraguay', 'ccode' => 'PY'],
             ['name' => 'Qatar', 'ccode' => 'QA'],
             ['name' => 'Réunion', 'ccode' => 'RE'],
             ['name' => 'Romania', 'ccode' => 'RO'],
             ['name' => 'Serbia', 'ccode' => 'RS'],
             ['name' => 'Russia', 'ccode' => 'RU'],
             ['name' => 'Rwanda', 'ccode' => 'RW'],
             ['name' => 'Saudi Arabia', 'ccode' => 'SA'],
             ['name' => 'Solomon Islands', 'ccode' => 'SB'],
             ['name' => 'Seychelles', 'ccode' => 'SC'],
             ['name' => 'Sudan', 'ccode' => 'SD'],
             ['name' => 'Sweden', 'ccode' => 'SE'],
             ['name' => 'Singapore', 'ccode' => 'SG'],
             ['name' => 'Saint Helena', 'ccode' => 'SH'],
             ['name' => 'Slovenia', 'ccode' => 'SI'],
             ['name' => 'Svalbard and Jan Mayen', 'ccode' => 'SJ'],
             ['name' => 'Slovakia', 'ccode' => 'SK'],
             ['name' => 'Sierra Leone', 'ccode' => 'SL'],
             ['name' => 'San Marino', 'ccode' => 'SM'],
             ['name' => 'Senegal', 'ccode' => 'SN'],
             ['name' => 'Somalia', 'ccode' => 'SO'],
             ['name' => 'Suriname', 'ccode' => 'SR'],
             ['name' => 'São Tomé and Príncipe', 'ccode' => 'ST'],
             ['name' => 'El Salvador', 'ccode' => 'SV'],
             ['name' => 'Syria', 'ccode' => 'SY'],
             ['name' => 'Swaziland', 'ccode' => 'SZ'],
             ['name' => 'Turks and Caicos Islands', 'ccode' => 'TC'],
             ['name' => 'Chad', 'ccode' => 'TD'],
             ['name' => 'French Southern Territories', 'ccode' => 'TF'],
             ['name' => 'Togo', 'ccode' => 'TG'],
             ['name' => 'Thailand', 'ccode' => 'TH'],
             ['name' => 'Tajikistan', 'ccode' => 'TJ'],
             ['name' => 'Tokelau', 'ccode' => 'TK'],
             ['name' => 'Timor-Leste', 'ccode' => 'TL'],
             ['name' => 'Turkmenistan', 'ccode' => 'TM'],
             ['name' => 'Tunisia', 'ccode' => 'TN'],
             ['name' => 'Tonga', 'ccode' => 'TO'],
             ['name' => 'Turkey', 'ccode' => 'TR'],
             ['name' => 'Trinidad and Tobago', 'ccode' => 'TT'],
             ['name' => 'Tuvalu', 'ccode' => 'TV'],
             ['name' => 'Taiwan', 'ccode' => 'TW'],
             ['name' => 'Tanzania', 'ccode' => 'TZ'],
             ['name' => 'Ukraine', 'ccode' => 'UA'],
             ['name' => 'Uganda', 'ccode' => 'UG'],
             ['name' => 'U.S. Minor Outlying Islands', 'ccode' => 'UM'],
             ['name' => 'United States', 'ccode' => 'US'],
             ['name' => 'Uruguay', 'ccode' => 'UY'],
             ['name' => 'Uzbekistan', 'ccode' => 'UZ'],
             ['name' => 'Vatican City', 'ccode' => 'VA'],
             ['name' => 'Saint Vincent and the Grenadines', 'ccode' => 'VC'],
             ['name' => 'Venezuela', 'ccode' => 'VE'],
             ['name' => 'British Virgin Islands', 'ccode' => 'VG'],
             ['name' => 'U.S. Virgin Islands', 'ccode' => 'VI'],
             ['name' => 'Vietnam', 'ccode' => 'VN'],
             ['name' => 'Vanuatu', 'ccode' => 'VU'],
             ['name' => 'Wallis and Futuna', 'ccode' => 'WF'],
             ['name' => 'Samoa', 'ccode' => 'WS'],
             ['name' => 'Kosovo', 'ccode' => 'XK'],
             ['name' => 'Yemen', 'ccode' => 'YE'],
             ['name' => 'Mayotte', 'ccode' => 'YT'],
             ['name' => 'South Africa', 'ccode' => 'ZA'],
             ['name' => 'Zambia', 'ccode' => 'ZM'],
             ['name' => 'Zimbabwe', 'ccode' => 'ZW'],

            
        ];

        DB::table('countries')->insert($countries);
    }
}
